[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

## Removed catch-all redirect to allow Next.js plugin to serve assets and routes

[functions]
  included_files = ["public/**/*"]

# Enable Next.js Runtime v5 forms support
[plugins.inputs]
  # Required when using HTML forms in /app with the Next.js Runtime v5
  # See https://ntl.fyi/next-runtime-forms-migration
  is_using_next_forms = true
